openapi: 3.1.0
info:
  title: Fourthwall APIs
  version: v1.0
  description: >
    # Overview


    ## Auth: Platform OAuth


    Right now, Platform OAuth is invite only. Please [contact
    us](https://docs.google.com/forms/d/1gRFnThFU8pq8Cfp3Rwy-hYS_mbUAvelu3bnER3DI8MY)
    to get access.


    We will need to know:

    1. Your redirect URL

    2. The permissions you need for the app    


    #### Authorize url


    Link your users to this url to start the login process for your app. Always
    use my-shop.fourthwall.com as the shop url as this will link to the logged
    in user's current shop.


    ```

    https://my-shop.fourthwall.com/admin/platform-apps/<YOUR_CLIENT_ID>/connect?redirect_uri=<YOUR_URL_ENCODED_REDIRECT_URL>

    ```


    #### Getting an access token 


    After the user has authorized your app, they will be redirected to your
    redirect URL with an authorization code.

    You will need to exchange this code for an access token.


    curl example:

    ```bash

    curl -XPOST
    https://auth.fourthwall.com/auth/realms/Fourthwall/protocol/openid-connect/token
    \
      -H "Content-Type: application/x-www-form-urlencoded" \
      -d "grant_type=authorization_code&redirect_uri=<YOUR_REDIRECT_URL>&client_id=<YOUR_CLIENT_ID>&client_secret=<YOUR_CLIENT_SECRET>&code=<AUTHORIZATION_CODE>" 
    ```


    The response will contain an `access_token`, `refresh_token`, and other
    information.


    #### Using the access token 


    curl example:

    ```bash

    curl -XGET https://api.fourthwall.com/open-api/v1/order/{YOUR_ORDER_ID} \
      -H "Authorization: Bearer YOUR_ACCESS_TOKEN"
    ```


    #### Refreshing the access token 


    Access tokens expire rather quickly (within 1 hour). You can use the
    refresh_token to get a new access token without having to re-authorize the
    user.


    curl example:

    ```bash

    curl -XPOST
    https://auth.fourthwall.com/auth/realms/Fourthwall/protocol/openid-connect/token
    \
      -H "Content-Type: application/x-www-form-urlencoded" \
      -d "grant_type=refresh_token&client_id=<YOUR_CLIENT_ID>&client_secret=<YOUR_CLIENT_SECRET>&refresh_token=<YOUR_REFRESH_TOKEN>"
    ```


    ## Auth: API key


    #### Getting credentials 


    Note that the creation of API credentials is reserved for users with the
    **SUPER ADMIN** role.


    1. Navigate to [For
    developers](https://my-shop.fourthwall.com/admin/dashboard/settings/for-developers)
    to create an API user.

    2. If API credentials haven't been generated yet, you will find a "Create
    API User" button under the "Open API" section. Click on it, and shortly
    after, the Username and Password for the Open API User will be provided.
      *Keep your API credentials confidential and do not share them with unauthorized personnel. These credentials grant access to sensitive data and actions within our system. Always use HTTPS/SSL for encrypted communication when making API requests.*

    #### Authorizing with credentials


    After Open API User was created, you can authorize your request by using
    **Basic Access Authentication**.


    This can be achieved by constructing an **Authorization** header with the
    format **Basic <base64-encoded-username-and-password>**. The base64-encoded
    credentials should be passed with each request to gain access to the
    protected resources.


    curl example:

    ```bash

    curl -u "your_username:your_password"
    http://api.fourthwall.com/open-api/v1/order/{YOUR_ORDER_ID}

    ```


    Javascript example:


    ```javascript

    const username = "your_username";

    const password = "your_password";


    // Combine username and password with a colon

    const combinedCredentials = `${username}:${password}`;


    // Encode the combined credentials to Base64

    const base64Credentials = btoa(combinedCredentials);


    const apiUrl =
    "http://api.fourthwall.com/open-api/v1/order/{YOUR_ORDER_ID}";

    const requestOptions = {
      method: "GET"
    };


    fetch(apiUrl, requestOptions)
      .then(response => response.json()) // Parse the JSON response directly
      .then(data => {
      // Handle the API response data here
      console.log(data);
    })
      .catch(error => {
      // Handle errors
      console.error("Error:", error);
    });

    ```


    ## Rate limiting policy


    To ensure fair usage and maintain optimal system performance, we have
    implemented rate limiting for API requests. This means that each user is
    allowed a maximum of **100 requests** within a **10-second rolling window**.


    **What it means for you:**


    - You can make up to 100 requests within any 10-second period.

    - If you exceed this limit, any additional requests will be delayed until
    the 10-second window is reset.

     Please plan your API usage accordingly to avoid interruptions and ensure the smooth functioning of our services.
        
    ## Products RSS feed


    If you're just looking to read public product information, you do not need
    to use Open API. All sites publish a Merchant Center Feed under an RSS
    address:


    ```

    {$shop_url}/.well-known/merchant-center/rss.xml

    ```


    **Example:** for [https://shop.fourthwall.com](https://shop.fourthwall.com)
    the RSS feed url would be
    [https://shop.fourthwall.com/.well-known/merchant-center/rss.xml](https://shop.fourthwall.com/.well-known/merchant-center/rss.xml)
servers:
  - url: https://api.fourthwall.com
    description: Generated server url
paths:
  /open-api/v1.0/donations:
    get:
      tags:
        - Donations
      summary: Get all donations
      description: Returns all donations with pagination
      operationId: getDonations
      security:
        - oauth:
            - donation_read
        - basicAuth: []
  /open-api/v1.0/donations/{donationId}:
    get:
      tags:
        - Donations
      summary: Get donation by id
      description: Returns donation by id
      operationId: getDonationById
      security:
        - oauth:
            - donation_read
        - basicAuth: []
  /open-api/v1.0/gifting/draw/{id}/finish:
    put:
      tags:
        - Gifting
      summary: Finish draw
      description: Finish draw and select winners
      operationId: drawFinished
      security:
        - basicAuth: []
  /open-api/v1.0/gifting/draw/{id}:
    get:
      tags:
        - Gifting
      summary: Get draw
      description: Get draw details
      operationId: getDraw
      security:
        - basicAuth: []
  /open-api/v1.0/giveaway-links:
    post:
      tags:
        - Giveaway links
      summary: Create giveaway links
      description: Creates a new package with specified number of giveaway links
      operationId: createGiveawayLinks
      security:
        - basicAuth: []
  /open-api/v1.0/giveaway-links/packages:
    get:
      tags:
        - Giveaway links
      summary: Get all giveaway packages
      description: Returns all packages with giveaway links
      operationId: getAllGiveawayLinksPackages
      security:
        - basicAuth: []
  /open-api/v1.0/giveaway-links/packages/{packageId}:
    get:
      tags:
        - Giveaway links
      summary: Get giveaway links
      description: Returns all giveaway links for packageId
      operationId: getGiveawayLinksByPackageId
      security:
        - basicAuth: []
  /open-api/v1.0/order:
    get:
      tags:
        - Orders
      summary: Get all orders
      description: Returns all orders with pagination
      operationId: getOrders
      security:
        - oauth:
            - order_read
        - basicAuth: []
  /open-api/v1.0/order/{orderId}:
    get:
      tags:
        - Orders
      summary: Get order by id
      description: Returns order by id
      operationId: getOrderByOrderId
      security:
        - oauth:
            - order_read
        - basicAuth: []
  /open-api/v1.0/order/by-friendly-id/{friendlyId}:
    get:
      tags:
        - Orders
      summary: Get order by friendly id
      description: Returns order by friendly id
      operationId: getOrderByFriendlyId
      security:
        - oauth:
            - order_read
        - basicAuth: []
  /open-api/v1.0/products/{productId}/availability:
    put:
      tags:
        - Products (offers)
      summary: Update product (offer) availability by id
      description: Updates a product (offer) availability
      operationId: updateOfferAvailability
      security:
        - oauth:
            - offer_write
        - basicAuth: []
  /open-api/v1.0/products:
    get:
      tags:
        - Products (offers)
      summary: Get all products (offers)
      description: Returns all products with pagination
      operationId: getProducts
      security:
        - oauth:
            - offer_read
        - basicAuth: []
  /open-api/v1.0/products/{productId}:
    get:
      tags:
        - Products (offers)
      summary: Get product (offer) by id
      description: Returns product by id
      operationId: getProductByProductId
      security:
        - oauth:
            - offer_read
        - basicAuth: []
  /open-api/v1.0/shops/current:
    get:
      tags:
        - Shop
      summary: Get current shop
      description: Returns the current shop
      operationId: getCurrentShop
      security:
        - oauth: []
        - basicAuth: []
  /open-api/v1.0/shops/current/contact-info:
    get:
      tags:
        - Shop
      summary: Get current shop contact info
      description: Returns the current shop contact info
      operationId: getCurrentShopContactInfo
      security:
        - oauth: []
        - basicAuth: []
  /open-api/v1.0/streaming/start:
    put:
      tags:
        - Streaming
      summary: Set streaming status to started
      description: Sets streaming status to started for specified services
      operationId: streamingStarted
      security:
        - basicAuth: []
  /open-api/v1.0/streaming/end:
    put:
      tags:
        - Streaming
      summary: Set streaming status to ended
      description: Sets streaming status to ended for specified services
      operationId: streamingEnded
      security:
        - basicAuth: []
  /open-api/v1.0/streaming:
    get:
      tags:
        - Streaming
      summary: Get streaming status
      description: Returns streaming status for all services
      operationId: streamingStatus
      security:
        - basicAuth: []
  /open-api/v1.0/thank-yous/{thankYouId}:
    get:
      tags:
        - Thank yous
      summary: Get Thank You by id
      description: Get Thank You details
      operationId: getGiftPurchaseById
      security:
        - oauth:
            - thankyou_read
        - basicAuth: []
  /open-api/v1.0/gift-purchase/{giftPurchaseId}:
    get:
      tags:
        - Twitch gift purchases
      summary: Get gift purchase by id
      description: Returns gift purchase details by id
      operationId: getGiftPurchaseById_1
      security:
        - basicAuth: []
  /open-api/v1.0/fulfillments:
    post:
      tags:
        - "BETA: Fulfillment"
      summary: Create a fulfillment for an order
      description: >-
        Creates a fulfillment with a shipment tracker for provided order items.
        When trackers change their state, order.status will change to
        IN_PRODUCTION, PARTIALLY_IN_PRODUCTION, PARTIALLY_SHIPPED, SHIPPED
        depending on the shipping tracker info. Order updated webhooks will be
        triggered.
      operationId: createFulfillment
      security:
        - oauth:
            - fulfillment_write
        - basicAuth: []
  /open-api/v1.0/fulfillments/{fulfillmentId}/shipping-labels:
    post:
      tags:
        - "BETA: Fulfillment"
      summary: Add shipping label to fulfillment
      description: >-
        Takes fulfillment_id, carrier name, tracking number and adds new
        shipping label to fulfillment. Optionally you can provide shipping
        method, tracker url and list items contained in particular shipping
        label.
      operationId: saveFulfillmentShippingLabel
      security:
        - oauth:
            - fulfillment_write
        - basicAuth: []
  /open-api/v1.0/fulfillments/find-by-friendly-id-and-fulfillment-service:
    post:
      tags:
        - "BETA: Fulfillment"
      summary: Find fulfillments ids by friendly ids and fulfillment service
      description: Find fulfillments ids by friendly ids and fulfillment service
      operationId: findFulfillmentIdsByFriendlyIdAndFulfillmentService
      security:
        - oauth:
            - fulfillment_write
        - basicAuth: []
  /open-api/v1.0/fulfillments/bulk/shipping-labels:
    post:
      tags:
        - "BETA: Fulfillment"
      summary: Bulk add shipping label to fulfillment
      description: >-
        Takes a list of fulfillment_id, carrier name, tracking number and adds
        new shipping label to fulfillment. Similar to
        saveFulfillmentShippingLabel but in bulk.
      operationId: bulkSaveFulfillmentsShippingLabels
      security:
        - oauth:
            - fulfillment_write
        - basicAuth: []
  /open-api/v1.0/promotions:
    get:
      tags:
        - "BETA: Promotions"
      summary: Get all promotions
      description: Returns all promotions
      operationId: getPromotions
      security:
        - oauth:
            - promotions_read
        - basicAuth: []
    post:
      tags:
        - "BETA: Promotions"
      summary: Create a promotion
      description: Creates a promotion
      operationId: createPromotion
      security:
        - oauth:
            - promotions_write
        - basicAuth: []
  /open-api/v1.0/webhooks/{webhookConfigurationId}:
    get:
      tags:
        - "BETA: Webhooks"
      summary: Get a webhook
      description: Get a webhook
      operationId: getWebhookConfiguration
    put:
      tags:
        - "BETA: Webhooks"
      summary: Update a webhook
      description: Update a webhook
      operationId: updateWebhookConfiguration
      security:
        - oauth:
            - webhook_write
        - basicAuth: []
    delete:
      tags:
        - "BETA: Webhooks"
      summary: Delete a webhook
      description: Delete a webhook
      operationId: deleteWebhookConfiguration
      security:
        - oauth:
            - webhook_write
        - basicAuth: []
  /open-api/v1.0/webhooks:
    get:
      tags:
        - "BETA: Webhooks"
      summary: Get webhooks
      description: Get webhooks
      operationId: getWebhookConfigurations
      security:
        - oauth:
            - webhook_read
        - basicAuth: []
    post:
      tags:
        - "BETA: Webhooks"
      summary: Create a webhook
      description: Create a webhook
      operationId: createWebhookConfiguration
      security:
        - oauth:
            - webhook_write
        - basicAuth: []
  /open-api/v1.0/webhooks-secret:
    get:
      tags:
        - "BETA: Webhooks"
      summary: Get webhook secret
      description: Get webhook secret
      operationId: getWebhookSecret
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: >-
            https://auth.fourthwall.com/auth/realms/Fourthwall/protocol/openid-connect/auth
          scopes:
            donation_read: donation_read
            order_read: order_read
            fulfillment_write: fulfillment_write
            promotions_write: promotions_write
            promotions_read: promotions_read
            offer_read: offer_read
            offer_write: offer_write
            shop_read: shop_read
            webhook_read: webhook_read
            webhook_write: webhook_write
    basicAuth:
      type: http
      scheme: basic
